name: Copy deployments to docs

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Contracts repository
        uses: actions/checkout@v4
        with:
          path: contracts

      - name: Checkout Docs repository
        uses: actions/checkout@v4
        with:
          repository: whetstoneresearch/doppler-docs
          token: ${{ secrets.PAT_DOCS }}
          path: docs

      - name: Copy deployments file from contracts to docs
        run: |
          cp contracts/Deployments.md docs/resources/contract-addresses.md

      - name: Commit and push to the docs repository
        run: |
          cd docs
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Check if there are changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Update deployments - ${{ github.sha }}"
            git push
          else
            echo "No changes to commit"
          fi
